# Java Maven CircleCI 2.0 configuration file
version: 2.1
jobs:
  ui-tests:
    docker:
      - image: cimg/openjdk:17.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Get chrome version
          command: google-chrome --version
      - run:
          name: Running tests
          command: mvn clean test
      - run:
          name: Generate allure report
          command: mvn allure:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
          when: always
      - store_artifacts:
          path: target/site/allure-maven-plugin/

workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
  periodical:
    triggers:
      - schedule:
          cron: "1 4,8,12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - ui-tests